name: Build TWRP (a3core)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    container:
      image: ghcr.io/minimal-manifest-twrp/twrp-docker:latest
      options: --user root

    steps:
    - name: Checkout device tree
      uses: actions/checkout@v4
      with:
        repository: GokuBlack557/twrp_device_samsung_a3core
        path: device/samsung/a3core

    - name: Clean build environment
      run: |
        cd /workspace
        echo "Cleaning old build files..."
        rm -rf out/* build/* device/* vendor/* || true
        df -h .

    - name: Prepare device tree
      run: |
        cd /workspace
        mkdir -p device/samsung
        mv $GITHUB_WORKSPACE/device/samsung/a3core device/samsung/a3core
        ls -lah device/samsung/a3core

    - name: Build recovery
      run: |
        cd /workspace
        . build/envsetup.sh
        if lunch twrp_a3core-eng 2>/dev/null; then
          echo "Using twrp_a3core-eng"
        elif lunch omni_a3core-eng 2>/dev/null; then
          echo "Using omni_a3core-eng"
        else
          echo "Lunch failed, showing combos:"
          lunch | head -n 50
          exit 1
        fi
        mka recoveryimage -j1
        echo "Output files:"
        ls -R out/target/product || true

    - name: Upload recovery artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-a3core-recovery
        path: |
          /workspace/out/target/product/*/recovery.img
          /workspace/out/target/product/*/twrp*.img
          /workspace/out/target/product/*/recovery-*.img

    - name: Upload logs (always)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: twrp-build-logs
        path: |
          /workspace/out/**
          /workspace/build/**
        if-no-files-found: ignore
