name: Build TWRP Recovery (Android 9)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3

    - name: Install repo tool
      run: |
        sudo curl -s https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+x /usr/local/bin/repo

    - name: Initialize TWRP repo (Android 9)
      run: |
        mkdir -p ~/twrp
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0 --depth=1
        repo sync -c --no-tags --no-clone-bundle -j$(nproc)

    # ✅ Step to check if the secret is being read
    - name: Debug GH_PAT
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        if [ -z "$GH_PAT" ]; then
          echo "❌ GH_PAT is EMPTY. Check your repository secrets."
          exit 1
        else
          echo "✅ GH_PAT is set properly."
        fi

    # ✅ Correct Git clone syntax using username + token
    - name: Clone device tree
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        cd ~/twrp
        git clone https://GokuBlack557:${GH_PAT}@github.com/GokuBlack557/twrp_device_samsung_a03core.git device/samsung/a03core

    - name: Build TWRP
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch omni_a03core-eng
        mka recoveryimage -j$(nproc)

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: ~/twrp/out/target/product/a03core/recovery.img
