name: TWRP Build (Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev libx11-dev libz-dev ccache \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python-is-python3

      - name: Initialize repo
        run: |
          mkdir ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

      - name: Sync source
        run: |
          cd ~/twrp
          repo sync -j$(nproc) --force-sync --no-tags --no-clone-bundle

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone https://github.com/SaneleSibiya/device_samsung_a2core.git device/samsung/a2core

      - name: Build recovery image
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C
          . build/envsetup.sh
          lunch twrp_a2core-eng
          mka recoveryimage -j$(nproc)

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: twrp-recovery
          path: out/target/product/a2core/recovery.img
