name: Build TWRP (a3core)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240   # stop if it runs longer than 4h
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show initial disk usage
        run: df -h && du -sh /usr/* | sort -h | tail -20

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          df -h

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z1-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python-is-python3

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize and sync repo
        run: |
          mkdir -p ~/twrp
          cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
          repo sync --force-sync --no-clone-bundle --no-tags -c -j2
          echo "Repo sync finished. Checking for build/envsetup.sh..."
          if [ ! -f build/envsetup.sh ]; then
            echo "ERROR: build/envsetup.sh not found!"
            ls -lah ~/twrp
            exit 1
          fi

      - name: Clone device tree
        run: |
          cd ~/twrp/device
          mkdir -p samsung
          cd samsung
          git clone https://github.com/GokuBlack557/twrp_device_samsung_a3core.git a3core

      - name: Build recovery
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_a3core-eng || lunch omni_a3core-eng
          mka recoveryimage -j2
          echo "Final out folder:"
          ls -R out/target/product || true

      - name: Upload recovery artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-recovery
          path: ~/twrp/out/target/product/*/recovery*.img
          if-no-files-found: error

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twrp-build-logs
          path: |
            ~/twrp/out/**
            ~/twrp/build/**
