name: TWRP Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH for GitHub
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          # write private key exactly as provided
          printf '%s\n' "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # add GitHub to known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # ensure git uses our key
          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=$HOME/.ssh/known_hosts"
          # test (non-fatal)
          ssh -T git@github.com || true

      - name: Verify SSH connection (verbose)
        run: ssh -vT git@github.com || true

      - name: Clone device tree
        run: |
          mkdir -p ~/twrp/device/samsung
          cd ~/twrp/device/samsung
          git clone git@github.com:GokuBlack557/twrp_device_samsung_a03core.git a03core

      - name: Verify clone success
        run: ls -la ~/twrp/device/samsung/a03core
