name: Build TWRP (a3core)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison build-essential \
        zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
        libncurses5-dev x11proto-core-dev libx11-dev libgl1-mesa-dev \
        libxml2-utils xsltproc unzip fontconfig python3 rsync ca-certificates wget

        # install repo tool
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "PATH=~/bin:$PATH" >> $GITHUB_ENV

    - name: Cache CCACHE
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Init repo
      run: |
        mkdir twrp && cd twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync -j$(nproc) --force-sync

    - name: Clone device tree
      run: |
        cd twrp
        git clone https://github.com/GokuBlack557/twrp_device_samsung_a3core.git device/samsung/a3core

    - name: Build TWRP
      run: |
        cd twrp
        source build/envsetup.sh
        lunch twrp_a3core-eng
        mka recoveryimage -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: twrp-a3core
        path: twrp/out/target/product/a3core/recovery.img
