name: Build TWRP (a3core)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl \
          zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev \
          x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc \
          unzip fontconfig python3 rsync ca-certificates wget openjdk-11-jdk

    - name: Install repo tool
      run: |
        mkdir -p $HOME/bin
        curl -sLo $HOME/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod a+x $HOME/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Sync TWRP source (shallow)
      run: |
        mkdir -p $HOME/twrp
        cd $HOME/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        repo sync --force-sync --no-clone-bundle --no-tags --depth=1 -j4 || true
        # save space
        find .repo -name ".git" -type d -exec rm -rf {} + || true

    - name: Clone device tree
      run: |
        cd $HOME/twrp
        git clone https://github.com/GokuBlack557/twrp_device_samsung_a3core.git device/samsung/a3core || true
        ls -lah device/samsung/a3core || true

    - name: Build recovery image
      run: |
        cd $HOME/twrp
        . build/envsetup.sh || true
        if lunch twrp_a3core-eng 2>/dev/null; then
          echo "Using twrp_a3core-eng"
        elif lunch omni_a3core-eng 2>/dev/null; then
          echo "Using omni_a3core-eng"
        else
          echo "Lunch failed, available combos:"
          lunch | head -n 50
          exit 1
        fi
        # slower but less disk I/O
        mka recoveryimage -j1 || true
        echo "Final out folder:"
        ls -R out/target/product || true

    - name: Upload recovery artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: twrp-a3core-recovery
        path: |
          $HOME/twrp/out/target/product/*/recovery.img
          $HOME/twrp/out/target/product/*/twrp*.img
          $HOME/twrp/out/target/product/*/recovery-*.img

    - name: Upload logs (always, for debugging)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: twrp-build-logs
        path: |
          $HOME/twrp/out/**
          $HOME/twrp/build/**
        if-no-files-found: ignore

