name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "Cleaning up space..."
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          df -h

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
            git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev \
            lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
            libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
            xsltproc zip zlib1g-dev libncurses5 libtinfo5
          df -h

      - name: Init repo
        run: |
          mkdir ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags

      - name: Device tree setup
        run: |
          cd ~/twrp
          git clone https://github.com/YOUR_DEVICE_TREE_HERE device/samsung/a03core

      - name: Lunch and build
        run: |
          cd ~/twrp
          . build/envsetup.sh
          lunch omni_a03core-eng
          make recoveryimage -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twrp-build
          path: |
            ~/twrp/out/target/product/*/recovery.img
            ~/twrp/out/target/product/*/boot.img
