name: Build TWRP (a3core)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show initial disk usage
      run: |
        echo "=== Disk usage before cleanup ==="
        df -h
        du -sh /usr/* 2>/dev/null | sort -h | tail -n 20

    - name: Free up space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
        echo "=== Disk usage after cleanup ==="
        df -h

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
        gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev \
        lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python-is-python3

    - name: Install repo tools
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Prepare TWRP source (shallow, current branch)
      run: |
        mkdir -p $HOME/twrp
        cd $HOME/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        repo sync --force-sync --no-clone-bundle --no-tags -c -j2
        echo "Repo sync finished. Checking for build/envsetup.sh..."
        if [ ! -f build/envsetup.sh ]; then
          echo "ERROR: build/envsetup.sh not found. Repo sync did not populate sources."
          ls -lah $HOME/twrp || true
          exit 1
        fi

    - name: Clone your device tree
      run: |
        cd $HOME/twrp
        git clone https://github.com/GokuBlack557/twrp_device_samsung_a3core.git device/samsung/a3core

    - name: Clean workspace before build
      run: |
        cd $HOME/twrp
        . build/envsetup.sh
        lunch twrp_a3core-eng
        mka clean

    - name: Build recovery image
      run: |
        cd $HOME/twrp
        . build/envsetup.sh
        lunch twrp_a3core-eng
        mka recoveryimage

    - name: Upload recovery artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: $HOME/twrp/out/target/product/*/recovery.img

    - name: Upload logs (always)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: $HOME/twrp/out/target/product/*/obj/* || true
