name: Build TWRP for Samsung A03 Core

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev \
          libz-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python-is-python3

    - name: Install repo command
      run: |
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+x /usr/local/bin/repo
        repo --version

    - name: Initialize TWRP source
      run: |
        mkdir -p ~/twrp
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b android-11 --depth=1

    - name: Add device sources
      run: |
        mkdir -p ~/twrp/.repo/local_manifests
        cat <<EOF > ~/twrp/.repo/local_manifests/a3core.xml
        <manifest>
          <project name="GokuBlack557/twrp_device_samsung_a3core" path="device/samsung/a3core" remote="github" revision="twrp-11" />
          <project name="GokuBlack557/kernel_samsung_a3core" path="kernel/samsung/a3core" remote="github" revision="twrp-11" />
          <project name="GokuBlack557/vendor_samsung_a3core" path="vendor/samsung/a3core" remote="github" revision="twrp-11" />
        </manifest>
        EOF

    - name: Sync source
      run: |
        cd ~/twrp
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync --current-branch -j4

    - name: Build TWRP
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch omni_a3core-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Recovery
        path: ~/twrp/out/target/product/*/recovery.img
