name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Show initial disk usage
        run: df -h

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          sudo apt clean
          df -h

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip

      - name: Initialize and sync repo
        run: |
          mkdir -p ~/twrp
          cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags -c

      - name: Configure ccache
        run: |
          export CCACHE_DIR=~/.ccache
          export CCACHE_EXEC=$(which ccache)
          ccache -M 5G
          ccache -s

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone https://github.com/YourUsername/twrp_device_yourdevice.git device/samsung/a03core

      - name: Build recovery
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_a03core-eng
          mka recoveryimage -j$(nproc)

      - name: Prepare output
        run: |
          mkdir -p output
          cp ~/twrp/out/target/product/*/recovery.img output/ || true

      - name: Upload recovery
        uses: actions/upload-artifact@v4
        with:
          name: twrp-build
          path: output/recovery.img

      - name: Show final disk usage
        run: df -h
