name: Build TWRP (a3core)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            libncurses5-dev x11proto-core-dev libx11-dev libgl1-mesa-dev \
            libxml2-utils xsltproc unzip fontconfig openjdk-8-jdk

      - name: Sync TWRP source
        run: |
          mkdir twrp && cd twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Clone device tree
        run: |
          cd twrp
          git clone https://github.com/GokuBlack557/twrp_a3core.git device/samsung/a3core

      - name: Build recovery
        run: |
          cd twrp
          source build/envsetup.sh
          lunch omni_a3core-eng
          mka recoveryimage || true

      - name: Upload recovery image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-a3core
          path: twrp/out/target/product/*/recovery.img

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: twrp/out
